- type: entity
  parent: CMBaseMachineCircuitboard
  id: CMSMESMachineCircuitboard
  name: "Машинна плата для малого та середнього бізнесу"
  description: "Машинна друкована плата для малого та середнього бізнесу."
  components:
  - type: Sprite
    state: power_mod
  - type: MachineBoard
    prototype: CMSMESEmpty
#    requirements:
#      Capacitor: 1
#      PowerCell: 4
#    materialRequirements:
#      CableHV: 10

- type: entity
  parent: CMBaseMachineCircuitboard
  id: CMAutolatheMachineCircuitboard
  name: "плата токарного верстата"
  description: "Друкована плата для токарного верстата"
  components: # TODO RMC14 autolathe
    - type: MachineBoard
      prototype: CMAutolathe
#      requirements:
#        MatterBin: 3
#        Manipulator: 1
#      materialRequirements:
#        CMGlass: 1

#- type: entity
#  parent: CMBaseMachineCircuitboard
#  id: CMPortableGeneratorPacmanMachineCircuitBoard
#  name: P.A.C.M.A.N.-type portable generator machine board
#  components:
#    - type: Sprite
#      state: power_mod
##    - type: MachineBoard
##      prototype: PortableGeneratorPacman # TODO RMC14 pacman
##      requirements:
##        Capacitor: 1
##      materialRequirements:
##        CableHV: 5
#    - type: PhysicalComposition
#      materialComposition:
#        CMGlass: 200
#      chemicalComposition:
#        Silicon: 20
#    - type: StaticPrice
#      price: 40

#- type: entity
#  parent: CMBaseMachineCircuitboard
#  id: CMPortableGeneratorSuperPacmanMachineCircuitboard
#  name: S.U.P.E.R.P.A.C.M.A.N.-type portable generator machine board
#  components:
#    - type: Sprite
#      state: power_mod
#    - type: MachineBoard
#      prototype: PortableGeneratorSuperPacman # TODO RMC14 super pacman
##      requirements:
##        Capacitor: 2
##      materialRequirements:
##        CableHV: 10
#    - type: PhysicalComposition
#      materialComposition:
#        CMGlass: 200
#      chemicalComposition:
#        Silicon: 20
#    - type: StaticPrice
#      price: 40

- type: entity
  parent: CMBaseMachineCircuitboard
  id: CMCircuitboardDispenserChem
  name: "плата машини для дозатора хімреагентів"
  description: "Машинна друкована плата для дозатора хімікатів."
  components:
  - type: Sprite
    state: blank_mod
  - type: MachineBoard
    prototype: RMCDispenserChemEmpty
    # TODO RMC14 material requirements

- type: entity
  parent: CMBaseMachineCircuitboard
  id: CMCircuitboardDispenserBooze
  name: "плата машини для розливу напоїв"
  description: "Машинна друкована плата для диспенсера для напоїв."
  components:
  - type: Sprite
    state: blank_mod
  - type: MachineBoard
    prototype: CMDispenserBoozeEmpty
    # TODO RMC14 material requirements

- type: entity
  parent: CMBaseMachineCircuitboard
  id: CMCircuitboardDispenserSoda
  name: "плата дозатора содової машини"
  description: "Машинна друкована плата для дозатора газованої води."
  components:
  - type: Sprite
    state: blank_mod
  - type: MachineBoard
    prototype: CMDispenserSodaEmpty
    # TODO RMC14 material requirements

- type: entity
  parent: CMBaseMachineCircuitboard
  id: CMCircuitboardChemMaster
  name: "плата машини chem master"
  description: "Машинна друкована плата для магістра хімії."
  components:
  - type: Sprite
    state: blank_mod
  - type: MachineBoard
    prototype: CMChemMaster
    # TODO RMC14 material requirements

- type: entity
  parent: CMBaseMachineCircuitboard
  id: CMCircuitboardMicrowave
  name: "плата мікрохвильової печі"
  description: "Машинна друкована плата для мікрохвильової печі."
  components:
  - type: Sprite
    state: blank_mod
  - type: MachineBoard
    prototype: CMMicrowave
#    # TODO RMC14 material requirements
