- type: job
  parent: CMJobSquadBase
  id: CMHospitalCorpsman
  name: cm-job-name-hospital-corpsman
  description: cm-job-description-hospital-corpsman
  playTimeTracker: CMJobHospitalCorpsman
  requirements:
  - !type:TotalJobsTimeRequirement
    group: CMJobsMedical
    time: 3600 # 1 hours
  - !type:DepartmentTimeRequirement
    department: CMSquad
    time: 3600 # 1 hour
  startingGear: CMGearHospitalCorpsman
  icon: "CMJobIconHospitalCorpsman"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  accessGroups:
  - HospitalCorpsman
  overwatchSortPriority: -1
  overwatchRoleName: Hospital Corpsmen
  minimapIcon:
    sprite: _RMC14/Interface/map_blips.rsi
    state: medic
  roleWeight: 1
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillJtac: 1
        RMCSkillMedical: 2
        RMCSkillSurgery: 1
    - type: CMVendorUser
      points: 45
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: "HM"

- type: startingGear
  id: CMGearHospitalCorpsman
  equipment:
    back: CMSatchelMarineMedic
    id: CMDogtagHospitalCorpsman

- type: startingGear
  id: CMGearHospitalCorpsmanEquipped
  equipment:
    jumpsuit: CMJumpsuitMarineMedic
    back: CMSatchelMarineMedic
    shoes: CMBootsBlackFilled
    gloves: CMHandsBlackMarine
    eyes: RMCGlassesMedicalHUDGlasses
    head: CMArmorHelmetM10Medic
    outerClothing: CMArmorM3Medium
    id: CMDogtagHospitalCorpsman
    ears: CMHeadsetAlphaMedic
    belt: CMBeltMedicBagFilled

- type: playTimeTracker
  id: CMJobHospitalCorpsman
  isHumanoid: true

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointHospitalCorpsman
  name: hospital corpsman spawn point
  components:
  - type: SpawnPoint
    job_id: CMHospitalCorpsman
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: hospital_corpsman

- type: entity
  parent: CMSpawnPointHospitalCorpsman
  id: CMSpawnPointHospitalCorpsmanAlpha
  suffix: Alpha
  components:
  - type: SquadSpawner
    squad: SquadAlpha
    role: CMHospitalCorpsman

- type: entity
  parent: CMSpawnPointHospitalCorpsman
  id: CMSpawnPointHospitalCorpsmanBravo
  suffix: Bravo
  components:
  - type: SquadSpawner
    squad: SquadBravo
    role: CMHospitalCorpsman

- type: entity
  parent: CMSpawnPointHospitalCorpsman
  id: CMSpawnPointHospitalCorpsmanCharlie
  suffix: Charlie
  components:
  - type: SquadSpawner
    squad: SquadCharlie
    role: CMHospitalCorpsman

- type: entity
  parent: CMSpawnPointHospitalCorpsman
  id: CMSpawnPointHospitalCorpsmanDelta
  suffix: Delta
  components:
  - type: SquadSpawner
    squad: SquadDelta
    role: CMHospitalCorpsman


