- type: job
  parent: CMJobSquadBase
  id: CMSmartGunOperator
  name: cm-job-name-smart-gun-operator
  description: cm-job-description-smart-gun-operator
  playTimeTracker: CMJobSmartGunOperator
  requirements:
    - !type:DepartmentTimeRequirement
      department: CMSquad
      time: 18000 # 5 hours
  startingGear: CMGearSmartGunOperator
  icon: "CMJobIconSmartGunOperator"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  accessGroups:
  - SmartGunOperator
  overwatchSortPriority: -2
  overwatchShowName: true
  overwatchRoleName: Smart Gun Operator
  minimapIcon:
    sprite: _RMC14/Interface/map_blips.rsi
    state: smartgunner
  roleWeight: 1
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillJtac: 1
        RMCSkillSmartGun: 1
    - type: CMVendorUser
      points: 45
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: "SG"

- type: startingGear
  id: CMGearSmartGunOperator
  equipment:
    id: CMDogtagSmartGunOperator

- type: startingGear
  id: CMGearSmartGunOperatorEquipped
  equipment:
    jumpsuit: JumpsuitMarine
    back: CMSatchelMarine
    shoes: CMBootsBlackFilled
    head: ArmorHelmetM10
    outerClothing: CMArmorM3Medium
    gloves: CMHandsBlackMarine
    id: CMDogtagSmartGunOperator
    ears: CMHeadsetAlpha

- type: playTimeTracker
  id: CMJobSmartGunOperator
  isHumanoid: true

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointSmartGunOperator
  name: smart gun operator spawn point
  components:
  - type: SpawnPoint
    job_id: CMSmartGunOperator
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: smart_gun_operator

- type: entity
  parent: CMSpawnPointSmartGunOperator
  id: CMSpawnPointSmartGunOperatorAlpha
  suffix: Alpha
  components:
  - type: SquadSpawner
    squad: SquadAlpha
    role: CMSmartGunOperator

- type: entity
  parent: CMSpawnPointSmartGunOperator
  id: CMSpawnPointSmartGunOperatorBravo
  suffix: Bravo
  components:
  - type: SquadSpawner
    squad: SquadBravo
    role: CMSmartGunOperator

- type: entity
  parent: CMSpawnPointSmartGunOperator
  id: CMSpawnPointSmartGunOperatorCharlie
  suffix: Charlie
  components:
  - type: SquadSpawner
    squad: SquadCharlie
    role: CMSmartGunOperator

- type: entity
  parent: CMSpawnPointSmartGunOperator
  id: CMSpawnPointSmartGunOperatorDelta
  suffix: Delta
  components:
  - type: SquadSpawner
    squad: SquadDelta
    role: CMSmartGunOperator

