- type: job
  parent: CMJobSquadBase
  id: CMSquadLeader
  name: cm-job-name-squad-leader
  description: cm-job-description-squad-leader
  playTimeTracker: CMJobSquadLeader
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMSquad
    time: 36000 # 10 hours
  startingGear: CMGearSquadLeader
  icon: "CMJobIconSquadLeader"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-co
  accessGroups:
  - SquadLeader
  overwatchSortPriority: -5
  overwatchShowName: true
  overwatchRoleName: Squad Leader
  minimapIcon:
    sprite: _RMC14/Interface/map_blips.rsi
    state: leader
  roleWeight: 1
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillCqc: 1
        RMCSkillEndurance: 2
        RMCSkillEngineer: 2
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillIntel: 1
        RMCSkillJtac: 2
        RMCSkillLeadership: 1
        RMCSkillMedical: 1
        RMCSkillVehicles: 1
    - type: CMVendorUser
      points: 45
    - type: MarineOrders
    - type: SquadArmorWearer
      leader: true
    - type: SquadLeader
    - type: RMCPointing
    - type: JobPrefix
      prefix: "SL"

- type: startingGear
  id: CMGearSquadLeader
  equipment:
    back: CMSatchelMarine
    id: CMDogtagSquadLeader

- type: startingGear
  id: CMGearSquadLeaderEquipped
  equipment:
    jumpsuit: JumpsuitMarine
    back: CMSatchelMarine
    shoes: CMBootsBlackFilled
    head: CMArmorHelmetM11
    outerClothing: CMArmorM3Medium
    gloves: CMHandsBlackMarine
    id: CMDogtagSquadLeader
    ears: CMHeadsetAlphaLeader

- type: playTimeTracker
  id: CMJobSquadLeader
  isHumanoid: true

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointSquadLeader
  name: squad leader spawn point
  components:
  - type: SpawnPoint
    job_id: CMSquadLeader
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: squad_leader

- type: entity
  parent: CMSpawnPointSquadLeader
  id: CMSpawnPointSquadLeaderAlpha
  suffix: Alpha
  components:
  - type: SquadSpawner
    squad: SquadAlpha
    role: CMSquadLeader

- type: entity
  parent: CMSpawnPointSquadLeader
  id: CMSpawnPointSquadLeaderBravo
  suffix: Bravo
  components:
  - type: SquadSpawner
    squad: SquadBravo
    role: CMSquadLeader

- type: entity
  parent: CMSpawnPointSquadLeader
  id: CMSpawnPointSquadLeaderCharlie
  suffix: Charlie
  components:
  - type: SquadSpawner
    squad: SquadCharlie
    role: CMSquadLeader

- type: entity
  parent: CMSpawnPointSquadLeader
  id: CMSpawnPointSquadLeaderDelta
  suffix: Delta
  components:
  - type: SquadSpawner
    squad: SquadDelta
    role: CMSquadLeader

