# combat technician
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidAlphaCombatTech
  name: "примарна роль бойового техніка альфа"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCAlphaCombatTech

- type: randomHumanoidSettings
  parent: [RMCCombatTech, RMCAlphaBase]
  id: RMCAlphaCombatTech

# fireteam leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidAlphaFireteamLeader
  name: "примарна роль командира вогневої групи альфа"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCAlphaFireteamLeader

- type: randomHumanoidSettings
  parent: [RMCFireteamLeader, RMCAlphaBase]
  id: RMCAlphaFireteamLeader

# hospital corpsman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidAlphaHospitalCorpsman
  name: "примарна роль санітара альфа"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCAlphaHospitalCorpsman

- type: randomHumanoidSettings
  parent: [RMCHospitalCorpsman, RMCAlphaBase]
  id: RMCAlphaHospitalCorpsman

# rifleman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidAlphaRifleman
  name: "примарна роль стрільця альфа"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCAlphaRifleman

- type: randomHumanoidSettings
  parent: [RMCRifleman, RMCAlphaBase]
  id: RMCAlphaRifleman

# smart gun operator
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidAlphaSmartGunOperator
  name: "примарна роль оператора смартгана альфа"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCAlphaSmartGunOperator

- type: randomHumanoidSettings
  parent: [RMCSmartGunOperator, RMCAlphaBase]
  id: RMCAlphaSmartGunOperator

# squad leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidAlphaSquadLeader
  name: "примарна роль командира відділення альфа"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCAlphaSquadLeader

- type: randomHumanoidSettings
  parent: [RMCSquadLeader, RMCAlphaBase]
  id: RMCAlphaSquadLeader

# weapons specialist
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidAlphaWeaponsSpecialist
  name: "примарна роль спеціаліста зі зброї альфа"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCAlphaWeaponsSpecialist

- type: randomHumanoidSettings
  parent: [RMCWeaponsSpecialist, RMCAlphaBase]
  id: RMCAlphaWeaponsSpecialist
