# combat technician
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaCombatTech
  name: "примарна роль бойового техніка дельта"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaCombatTech

- type: randomHumanoidSettings
  parent: [RMCCombatTech, RMCDeltaBase]
  id: RMCDeltaCombatTech

# fireteam leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaFireteamLeader
  name: "примарна роль командира вогневої групи дельта"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaFireteamLeader

- type: randomHumanoidSettings
  parent: [RMCFireteamLeader, RMCDeltaBase]
  id: RMCDeltaFireteamLeader

# hospital corpsman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaHospitalCorpsman
  name: "примарна роль санітара дельта"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaHospitalCorpsman

- type: randomHumanoidSettings
  parent: [RMCHospitalCorpsman, RMCDeltaBase]
  id: RMCDeltaHospitalCorpsman

# rifleman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaRifleman
  name: "примарна роль стрільця дельта"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaRifleman

- type: randomHumanoidSettings
  parent: [RMCRifleman, RMCDeltaBase]
  id: RMCDeltaRifleman

# smart gun operator
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaSmartGunOperator
  name: "примарна роль оператора смартгана дельта"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaSmartGunOperator

- type: randomHumanoidSettings
  parent: [RMCSmartGunOperator, RMCDeltaBase]
  id: RMCDeltaSmartGunOperator

# squad leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaSquadLeader
  name: "примарна роль командира відділення дельта"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaSquadLeader

- type: randomHumanoidSettings
  parent: [RMCSquadLeader, RMCDeltaBase]
  id: RMCDeltaSquadLeader

# weapons specialist
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaWeaponsSpecialist
  name: "примарна роль спеціаліста зі зброї дельта"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaWeaponsSpecialist

- type: randomHumanoidSettings
  parent: [RMCWeaponsSpecialist, RMCDeltaBase]
  id: RMCDeltaWeaponsSpecialist
