- type: job
  abstract: true
  id: CMJobBase
  isCM: true
  canBeAntag: false

- type: job
  abstract: true
  parent: CMJobBase
  id: CMJobSquadBase
  hasSquad: true

- type: department
  abstract: true
  id: CMDepartmentBase
  isCM: true

# Xeno
- type: job
  abstract: true
  parent: CMJobBase
  id: CMJobXenoBase
  description: null
  joinNotifyCrew: false
  icon: "CMJobIconEmpty"
  supervisors: cm-job-supervisors-queen
  accessGroups:
  - CMAccessXeno
  hasIcon: false
  hidden: true

- type: entity
  parent: MarkerBase
  id: CMSpawnPointXeno
  name: "точка розмноження ксеносів"
  description: "Розплідник RMC14. Використовується для ксеносів."
  components:
  - type: XenoSpawnPoint
  - type: Sprite
    sprite: _RMC14/Markers/landmarks.rsi
    state: xeno_spawn

- type: entity
  parent: MarkerBase
  id: CMSpawnPointXenoLeader
  name: "точка зародження лідера ксеносів"
  description: "Розплідник RMC14. Використовується для ксеносів Квінс."
  components:
  - type: XenoLeaderSpawnPoint
  - type: Sprite
    sprite: _RMC14/Markers/landmarks.rsi
    state: queen_spawn
