- type: job
  parent: CMJobBase
  id: CMChiefEngineer
  name: cm-job-name-chief-engineer
  description: cm-job-description-chief-engineer
  playTimeTracker: CMJobChiefEngineer
  requirements:
  - !type:TotalJobsTimeRequirement
    group: CMJobsEngineering
    time: 36000 # 10 hours
  weight: 5
  startingGear: CMGearChiefEngineer
  icon: "CMJobIconChiefEngineer"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-aso
  accessGroups:
  - CMCE
  minimapIcon:
    sprite: _RMC14/Interface/map_blips.rsi
    state: ce
  minimapBackground:
   sprite: _RMC14/Interface/map_blips.rsi
   state: background_command
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 3
        RMCSkillEngineer: 3
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillIntel: 1
        RMCSkillJtac: 4
        RMCSkillLeadership: 3
        RMCSkillNavigations: 1
        RMCSkillOverwatch: 1
        RMCSkillPolice: 1
        RMCSkillPowerLoader: 2
    - type: MarineOrders
    - type: RMCPointing
    - type: JobPrefix
      prefix: "CE"

- type: startingGear
  id: CMGearChiefEngineer
  equipment:
    jumpsuit: CMJumpsuitChiefEngineer
    back: CMSatchelMarineTech
    shoes: CMBootsBlack
    gloves: CMHandsInsulated
    id: CMIDCardChiefEngineer
    ears: CMHeadsetCE
    belt: CMBeltUtilityFilled
    pocket1: RMCPouchElectronics

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointChiefEngineer
  name: chief engineer spawn point
  components:
  - type: SpawnPoint
    job_id: CMChiefEngineer
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: chief_engineer

- type: playTimeTracker
  id: CMJobChiefEngineer
  isHumanoid: true
