- type: entity
  name: "скринька для чистокровних"
  parent: BoxCardboard
  id: BoxCleanerGrenades
  description: "Коробка, повна чистотілу."
  components:
  - type: StorageFill
    contents:
      - id: CleanerGrenade
        amount: 4
  - type: Sprite
    layers:
      - state: box
      - state: flashbang

- type: entity
  name: "Набір NT \"Агрохімія - це весело"
  parent: BoxCardboard
  id: BoxAgrichem
  description: "Для ботаніка-початківця, який хоче дізнатися про максимізацію врожайності на фермі. Цій вицвілій коробці має бути щонайменше 50 років."
  components:
  - type: StorageFill
    contents:
    - id: PaperAgrichemManual
    - id: ChemistryEmptyBottle01
    - id: PotassiumChemistryBottle
    - id: PhosphorusChemistryBottle
    - id: NitrogenChemistryBottle
    - id: HydrogenChemistryBottle
    - id: EthanolChemistryBottle
    - id: RadiumChemistryVial
    - id: ChlorineChemistryVial
  - type: Sprite
    layers:
      - state: boxwide
      - state: agrichemkit
  - type: GuideHelp
    guides:
    - Botanical
    - Chemicals
