- type: startingGear
  id: RMCGearSurvivorSecurity
  equipment:
    head: CMHeadBeretRed
    jumpsuit: CMJumpsuitColonist # /obj/item/clothing/under/rank/security
    back: CMSatchelSecurity
    shoes: CMBootsBlack # jackboots
    id: CMIDCardColonist
    ears: CMHeadsetColony
    pocket1: RMCM5Bayonet
    pocket2: RMCFlashlight

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorSecurity
  name: "точка спавну безпеки для тих, хто вижив"
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: survivor
