- type: entity
  parent: MarkerBase
  id: RMCMapInsertBase
  abstract: true
  name: "База для вставки карти"
  components:
  - type: Sprite
    sprite: _RMC14/Markers/landmarks.rsi
    state: nightmare_insert
