- type: job
  parent: CMJobBase
  id: CMChiefMP
  name: cm-job-name-chief-mp
  description: cm-job-description-chief-mp
  playTimeTracker: CMJobChiefMP
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMMilitaryPolice
    time: 54000 # 15 hours
  - !type:DepartmentTimeRequirement
    department: CMCommand
    time: 18000 # 5 hours
  weight: 5
  startingGear: CMGearChiefMP
  icon: "CMJobIconChiefMP"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-co
  accessGroups:
  - CMP
  minimapIcon:
    sprite: _RMC14/Interface/map_blips.rsi
    state: cmp
  minimapBackground:
   sprite: _RMC14/Interface/map_blips.rsi
   state: background_mp
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillCqc: 2
        RMCSkillEndurance: 2
        RMCSkillEngineer: 2
        RMCSkillFirearms: 1
        RMCSkillFireman: 2
        RMCSkillIntel: 1
        RMCSkillJtac: 3
        RMCSkillLeadership: 2
        RMCSkillMedical: 1
        RMCSkillMeleeWeapons: 1
        RMCSkillOverwatch: 1
        RMCSkillPolice: 2
    - type: MarineOrders
    - type: RMCPointing
    - type: JobPrefix
      prefix: "CMP"

- type: startingGear
  id: CMGearChiefMP
  equipment:
    jumpsuit: CMJumpsuitWO
    back: CMSatchelSecurity
    shoes: CMBootsBlackFilled
    head: CMHeadBeretWO
    eyes: CMGlassesSecurity
    gloves: CMHandsBlackMarine
    id: CMIDCardChiefMP
    outerClothing: CMArmorM3WO
    ears: CMHeadsetCMP
    belt: CMBeltSecurityMPFilled
    #    pocket1: TODO RMC14 tape recorder
    pocket2: RMCPouchGeneralLarge

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointChiefMP
  name: chief mp spawn point
  components:
  - type: SpawnPoint
    job_id: CMChiefMP
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: chief_military_police

- type: playTimeTracker
  id: CMJobChiefMP
  isHumanoid: true
