- type: entity
  id: BaseMindRole
  name: "Роль розуму"
  description: "Розумна рольова сутність"
  abstract: true
  components:
  - type: MindRole

- type: entity
  parent: BaseMindRole
  id: BaseMindRoleAntag
  abstract: true
  components:
  - type: MindRole
    antag: true

#Observer
- type: entity
  parent: BaseMindRole
  id: MindRoleObserver
  name: "Роль спостерігача"
  components:
  - type: ObserverRole

#Ghostrole Marker
- type: entity
  parent: BaseMindRole
  id: MindRoleGhostMarker
  name: "Роль примари"
  components:
  - type: GhostRoleMarkerRole

# The Job MindRole holds the mob's Job prototype
- type: entity
  parent: BaseMindRole
  id: MindRoleJob
  name: "Посадові обов'язки"
#  description:
  # MindRoleComponent.JobPrototype is filled by SharedJobSystem

# Subverted Silicon
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSubvertedSilicon
  name: "Підривна роль кремнію"
  description:
  components:
  - type: SubvertedSiliconRole
  - type: MindRole
    antagPrototype: SubvertedSilicon

# Dragon
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleDragon
  name: "Роль дракона"
#  description:
  components:
  - type: MindRole
    antagPrototype: Dragon
    exclusiveAntag: true
  - type: DragonRole
  - type: RoleBriefing
    briefing: dragon-role-briefing

# Ninja
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleNinja
  name: "Роль космічного ніндзя"
#  description: mind-role-ninja-description
  components:
  - type: MindRole
    antagPrototype: SpaceNinja
    exclusiveAntag: true
  - type: NinjaRole

# Nukies
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleNukeops
  name: "Оперативна роль Nukeops"
#  description: mind-role-nukeops-description
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: Nukeops
  - type: NukeopsRole

- type: entity
  parent: MindRoleNukeops
  id: MindRoleNukeopsMedic
  name: "Роль медика Nukeops"
#  description: mind-role-nukeops-medic-description
  components:
  - type: MindRole
    antagPrototype: NukeopsMedic

- type: entity
  parent: MindRoleNukeops
  id: MindRoleNukeopsCommander
  name: "Роль командира Nukeops"
#  description: mind-role-nukeops-commander-description
  components:
  - type: MindRole
    antagPrototype: NukeopsCommander

# Revolutionaries
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleHeadRevolutionary
  name: "Роль головного революціонера"
#  description: mind-role-head-revolutionary-description
  components:
  - type: MindRole
    antagPrototype: HeadRev
    exclusiveAntag: true
  - type: RevolutionaryRole

- type: entity
  parent: MindRoleHeadRevolutionary
  id: MindRoleRevolutionary
  name: "Революційна роль"
#  description: mind-role-revolutionary-description
  components:
  - type: MindRole
    antagPrototype: Rev

# Thief
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleThief
  name: "Роль злодія"
#  description: mind-role-thief-description
  components:
  - type: MindRole
    antagPrototype: Thief
  - type: ThiefRole

# Traitors
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleTraitor
  name: "Роль зрадника"
#  description: mind-role-traitor-description
  components:
  - type: MindRole
    antagPrototype: Traitor
    exclusiveAntag: true
  - type: TraitorRole

- type: entity
  parent: MindRoleTraitor
  id: MindRoleTraitorSleeper
  name: "Роль сплячого агента"
#  description: mind-role-traitor-sleeper-description
  components:
  - type: MindRole
    antagPrototype: TraitorSleeper

# Zombie Squad
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleInitialInfected
  name: "Початкова роль інфікованого"
#  description: mind-role-initial-infected-description
  components:
  - type: MindRole
    antagPrototype: InitialInfected
    exclusiveAntag: true
  - type: InitialInfectedRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleZombie
  name: "Роль зомбі"
#  description: mind-role-zombie-description
  components:
  - type: MindRole
    antagPrototype: Zombie
    exclusiveAntag: true
  - type: ZombieRole
