- type: rank
  id: RMCRankCivilian
  name: "Цивільний"
  prefix: Civ.
  malePrefix: Mr.
  femalePrefix: Ms.

- type: rank
  id: RMCRankCivilianNurse
  name: "Медсестро!"
  prefix: Nrs.

- type: rank
  id: RMCRankCivilianDoctor
  name: "Лікарю"
  prefix: Dr.

- type: rank
  id: RMCRankCivilianProfessor
  name: "Професор"
  prefix: Prof.

- type: rank
  id: RMCRankCivilianRepresentative
  name: "Представник"
  prefix: Rep.

- type: rank
  id: RMCRankCivilianOfficer
  name: "Офіцере!"
  prefix: Off.

- type: rank
  id: RMCRankCivilianSeniorOfficer
  name: "Старший офіцер"
  prefix: Sr. Off.
